#!/bin/bash
filename="plot_naive.csv"

#echo "Enter a polynomial:"
#read name
#./Main "$name" $filename
dist/build/naive/naive "$(< old_poly.txt)" $filename
cp -f $filename sketch_3D_Interval_Analysis/data/my_poly_naive.csv
scripts/run sketch_3D_Interval_Analysis
